
site_name: Astra Documentation
site_url: https://terrapin-rocket-team.github.io/Astra/
repo_url: https://github.com/Terrapin-Rocket-Team/Astra
repo_name: Terrapin-Rocket-Team/Astra
repo_version: "0.2"
theme:
  icon:
    repo: fontawesome/brands/github
    annotation: material/help-rhombus
  custom_dir: overrides
  font:
    text: Poppins
  name: material
  palette:     
    # - media: "(prefers-color-scheme: light)"
    #   scheme: default
    #   toggle:
    #     icon: material/brightness-7
    #     name: Switch to dark mode
    #   primary: custom
    #   accent: custom

    # - media: "(prefers-color-scheme: dark)"
      scheme: slate
      # toggle:
      #   icon: material/brightness-4
      #   name: Switch to light mode
      primary: custom
      accent: custom
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.top
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.sections
    - navigation.path
    - content.code.copy
    - content.code.annotate
    - header.autohide
    - navigation.footer
    - navigation.expand
    - content.footnote.tooltips
  


extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true
      linenums: true
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.blocks.tab:
      alternate_style: true
  - admonition
  - pymdownx.tilde
  - footnotes
  - attr_list
  - md_in_html
      
plugins:
  - search
  - awesome-pages #not a real error
  - autolinks
